config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'

  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns title of page
    def full_title(page_title = '')
        base_title = ""
        if page_title.empty?
            base_title
        else
            base_title + " | " + page_title
        end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_application_layout.html.erb
<body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <% #debug(params) if Rails.env.development? %>
    </div>
</body>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-static-top">
    <div class="container-center">
        <div class="container" id="logo">#</div>
    </div>
    <br>
    <div class="container-center">
        <nav>
            <ul class="nav navbar-nav">
                <li><%= link_to "Home", root_path, id: "logo-three" %></li>
                <li><%= link_to "About", about_path, id: "logo-three" %></li>
                <li><%= link_to "Contact", contact_path, id: "logo-three" %></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 
                                'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
      <%= render 'layouts/header' %>
  </head>
    <body>
    <%= render 'layouts/application_layout' %>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>